### ISSUE TITLE
Lists are incorrectly formatted

### ISSUE THREAD

**Issue by ddormer** [ddormer/markdown-to-bbcode#3]
Another issue is that lists are incorrectly formatted.

Input:

```
## Frequently Asked Questions:

- Q: Question one.
- A: Answer one.

- Q: Question two.
- A: Answer two.
```

Output:

```
[b][size=6]Frequently Asked Questions:[/size][/b]
[list]
[*]
Q: Question one.

[*]
A: Answer one.

[*]
Q: Question two.

[*]
A: Answer two.

[/list]
```

Expected output (best):

```
[b][size=6]Frequently Asked Questions:[/size][/b]

[list]
[*]Q: Question one.
[*]A: Answer one.
[/list]

[list]
[*]Q: Question two.
[*]A: Answer two.
[/list]
```

Expected output (acceptable but not as good):

```
[b][size=6]Frequently Asked Questions:[/size][/b]

[list]
[*]Q: Question one.
[*]A: Answer one.

[*]Q: Question two.
[*]A: Answer two.
[/list]
```

I don't say this to criticize. Just to let you know about these formatting issues. Your converter is probably the best one out there anyway, since everything else I found created completely unusable output. :)

_Originally posted by @Bananaman in https://github.com/ddormer/markdown-to-bbcode/issues/1#issuecomment-1059755038_

**Comment by ddormer** [comment]
This appears to be expected output according to the spec: https://spec.commonmark.org/0.30/#loose

Their suggestion for breaking separating lists is to use an empty HTML comment `<!-- -->` but unfortunately BBCode doesn't have comments.

**Comment by ddormer** [comment]
An immediate solution to this would be to use syntax like:
```
- item 1
- item 2

* item 3
* item 4
```
where the lists are alternating between a dash and asterix.

**Comment by Arcitec** [comment]
Huh, that's fascinating. I never knew that empty newlines are legal in markdown lists. I have encountered sites that treated newlines as new lists, for example the following:

```
1. A

2. B

3. C
```

Would be rendered by certain sites as:

```
1. A

1. B

1. C
```

Because it sees every newline separator as a new list and restarts the numbering from 1 when rendering the markdown.

So I became used to thinking "newlines are not allowed in markdown".

Thanks for finding the spec and the workaround. It actually makes sense to allow newlines since it helps with creating nicer formatting when reading the file as plaintext.

The workaround works perfectly in your renderer, too. :+1: :)

I noticed that the spec for markdown had a bunch of rules about adding `<p>` around list blocks that were separated by newlines (loose lists), as seen in example 306 and down: https://spec.commonmark.org/0.30/#example-306

I think it's meant to help with rendering, somehow... But bbcode lists don't have any equivalent of `<p>` so it makes no sense either way.

Seems like the most correct bbcode translation of markdown's intended behavior will be to treat newlines as nothing at all, and merging it as part of the same list, as your parser does. I guess this ticket can be closed. :)
